model_folder: the/path/to/your/body/models # body model folder path
motion_path: assets/example_motion/sample_motion_data_smpl.npz # motion npz file path
camera_config: configs/kinect.json # camera parameters file path 